In [340]:
from core import pattern
import numpy as np
from copy import copy

# Creating a pattern object from arbitrary data

In [341]:
pat = pattern()
print(pat)

<xarray.DataArray (field: 0, frequency: 0, theta: 0, phi: 0)>
array([], shape=(0, 0, 0, 0), dtype=float64)
Dimensions without coordinates: field, frequency, theta, phi


In [342]:
data = np.asarray(
    [[[
        [0, 1, 2, 3],
        [4, 5, 6, 7]
    ]]]
)
coords = {
    'field': ['Re_Ephi'],
    'frequency' : [1e9],
    'theta' : [0, 90],
    'phi' : [0, 90, 180, 270]
}
pat = pattern(data, coords)
print(pat)

<xarray.DataArray (field: 1, frequency: 1, theta: 2, phi: 4)>
array([[[[0, 1, 2, 3],
         [4, 5, 6, 7]]]])
Coordinates:
  * field      (field) <U7 'Re_Ephi'
  * frequency  (frequency) float64 1e+09
  * theta      (theta) int32 0 90
  * phi        (phi) int32 0 90 180 270


In [343]:
re_ephi_data = np.asarray(
    [[
        [0, 1, 2, 3],
        [4, 5, 6, 7]
    ]]
)
im_ephi_data = np.asarray(
    [[
        [4, 5, 6, 7],
        [0, 1, 2, 3],
    ]]
)

pat = pattern(
    Re_Ephi=re_ephi_data,
    Im_Ephi=im_ephi_data,
    frequency=[1e9],
    theta=[0, 90],
    phi=[0, 90, 180, 270]
)
print(pat)

<xarray.DataArray (field: 2, frequency: 1, theta: 2, phi: 4)>
array([[[[0., 1., 2., 3.],
         [4., 5., 6., 7.]]],


       [[[4., 5., 6., 7.],
         [0., 1., 2., 3.]]]])
Coordinates:
  * frequency  (frequency) float64 1e+09
  * theta      (theta) int32 0 90
  * phi        (phi) int32 0 90 180 270
  * field      (field) <U7 'Re_Ephi' 'Im_Ephi'


# Default dimensions, fields, units

In [344]:
pattern.DEFAULT_DIMS

['field', 'frequency', 'theta', 'phi']

In [345]:
pattern.DEFAULT_UNITS

{'Frequency': 'Hz',
 'Theta': 'deg',
 'Phi': 'deg',
 'Elevation': 'deg',
 'Azimuth': 'deg',
 'Re_Etheta': 'V/m',
 'Im_Etheta': 'V/m',
 'Re_Ephi': 'V/m',
 'Im_Ephi': 'V/m',
 'Re_Htheta': 'A/m',
 'Im_Htheta': 'A/m',
 'Re_Hphi': 'A/m',
 'Im_Hphi': 'A/m',
 'Directivity_Theta': 'dBi',
 'Directivity_Phi': 'dBi',
 'Directivity_Total': 'dBi',
 'Directivity_L3X': 'dBi',
 'Directivity_L3Y': 'dBi',
 'Directivity_LHCP': 'dBic',
 'Directivity_RHCP': 'dBic',
 'Gain_Theta': 'dBi',
 'Gain_Phi': 'dBi',
 'Gain_Total': 'dBi',
 'Gain_L3X': 'dBi',
 'Gain_L3Y': 'dBi',
 'Gain_LHCP': 'dBic',
 'Gain_RHCP': 'dBic',
 'Realized_Gain_Theta': 'dBi',
 'Realized_Gain_Phi': 'dBi',
 'Realized_Gain_Total': 'dBi',
 'Realized_Gain_L3X': 'dBi',
 'Realized_Gain_L3Y': 'dBi',
 'Realized_Gain_LHCP': 'dBic',
 'Realized_Gain_RHCP': 'dBic',
 'Xpol_Ratio_Y_to_X': 'dB',
 'Xpol_Ratio_X_to_Y': 'dB',
 'Xpol_Ratio_LH_to_RH': 'dB',
 'Xpol_Ratio_RH_to_LH': 'dB',
 'Axial_Ratio': 'dB',
 'Polarization_Angle': 'deg'}

In [346]:
pattern.VALID_FIELD_NAMES

['Re_Etheta',
 'Im_Etheta',
 'Re_Ephi',
 'Im_Ephi',
 'Re_Htheta',
 'Im_Htheta',
 'Re_Hphi',
 'Im_Hphi',
 'Directivity_Theta',
 'Directivity_Phi',
 'Directivity_Total',
 'Directivity_L3X',
 'Directivity_L3Y',
 'Directivity_LHCP',
 'Directivity_RHCP',
 'Gain_Theta',
 'Gain_Phi',
 'Gain_Total',
 'Gain_L3X',
 'Gain_L3Y',
 'Gain_LHCP',
 'Gain_RHCP',
 'Realized_Gain_Theta',
 'Realized_Gain_Phi',
 'Realized_Gain_Total',
 'Realized_Gain_L3X',
 'Realized_Gain_L3Y',
 'Realized_Gain_LHCP',
 'Realized_Gain_RHCP',
 'Xpol_Ratio_Y_to_X',
 'Xpol_Ratio_X_to_Y',
 'Xpol_Ratio_LH_to_RH',
 'Xpol_Ratio_RH_to_LH',
 'Axial_Ratio',
 'Polarization_Angle']

# Converting coordinate systems

In [347]:
print('Initial coordinates: ')
print(pat)

Initial coordinates: 
<xarray.DataArray (field: 2, frequency: 1, theta: 2, phi: 4)>
array([[[[0., 1., 2., 3.],
         [4., 5., 6., 7.]]],


       [[[4., 5., 6., 7.],
         [0., 1., 2., 3.]]]])
Coordinates:
  * frequency  (frequency) float64 1e+09
  * theta      (theta) int32 0 90
  * phi        (phi) int32 0 90 180 270
  * field      (field) <U7 'Re_Ephi' 'Im_Ephi'


In [348]:
print('Az-el coordinates: ')
pat_az_el = copy(pat)
pat_az_el.sph_2_az_el()
print(pat_az_el)

Az-el coordinates: 
<xarray.DataArray (field: 2, frequency: 1, elevation: 2, azimuth: 4)>
array([[[[0., 1., 2., 3.],
         [4., 5., 6., 7.]]],


       [[[4., 5., 6., 7.],
         [0., 1., 2., 3.]]]])
Coordinates:
  * frequency  (frequency) float64 1e+09
  * elevation  (elevation) int32 90 0
  * azimuth    (azimuth) int32 0 90 180 270
  * field      (field) <U7 'Re_Ephi' 'Im_Ephi'


In [349]:
print('Array coordinates:')
pat_array = copy(pat)
pat_array.sph_2_array_coordinates()
print(pat_array)

Array coordinates:
<xarray.DataArray (field: 2, frequency: 1, theta: 3, phi: 3)>
array([[[[ 2.,  3., nan],
         [ 0.,  1.,  2.],
         [ 4.,  5.,  6.]]],


       [[[ 6.,  7., nan],
         [ 4.,  5.,  6.],
         [ 0.,  1.,  2.]]]])
Coordinates:
  * phi        (phi) int64 0 90 180
  * frequency  (frequency) float64 1e+09
  * theta      (theta) int64 -90 90 0
  * field      (field) <U7 'Re_Ephi' 'Im_Ephi'
